# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addEditCoffeeForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class UiAddWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        MainWindow.setMinimumSize(QtCore.QSize(400, 400))
        MainWindow.setMaximumSize(QtCore.QSize(400, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 300, 381, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, 320, 381, 16))
        self.label_5.setObjectName("label_5")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setGeometry(QtCore.QRect(10, 140, 381, 131))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.label_2 = QtWidgets.QLabel(self.splitter)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.check_text_lineedit = QtWidgets.QLineEdit(self.splitter)
        self.check_text_lineedit.setObjectName("check_text_lineedit")
        self.label_3 = QtWidgets.QLabel(self.splitter)
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.update_lineedit = QtWidgets.QLineEdit(self.splitter)
        self.update_lineedit.setObjectName("update_lineedit")
        self.update_btn = QtWidgets.QPushButton(self.splitter)
        self.update_btn.setObjectName("update_btn")
        self.splitter_2 = QtWidgets.QSplitter(self.centralwidget)
        self.splitter_2.setGeometry(QtCore.QRect(10, 20, 381, 101))
        self.splitter_2.setOrientation(QtCore.Qt.Vertical)
        self.splitter_2.setObjectName("splitter_2")
        self.label = QtWidgets.QLabel(self.splitter_2)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.add_lineedit = QtWidgets.QLineEdit(self.splitter_2)
        self.add_lineedit.setObjectName("add_lineedit")
        self.add_btn = QtWidgets.QPushButton(self.splitter_2)
        self.add_btn.setObjectName("add_btn")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 0, 381, 21))
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "add"))
        self.label_4.setText(_translate("MainWindow", "Пример записи во все QlineEdit:"))
        self.label_5.setText(_translate("MainWindow", "666;Арабика;Средняя;Молотый;Вкусный;200;100"))
        self.label_2.setText(_translate("MainWindow", "Введите данные о кофе, которые хотите изменить через ; "))
        self.label_3.setText(_translate("MainWindow", "ID менять нельзя. Введите ниже строчку с изменениями"))
        self.update_btn.setText(_translate("MainWindow", "Изменить"))
        self.label.setText(_translate("MainWindow", "При добавлении не используйте ID, которые уже есть в таблице"))
        self.add_btn.setText(_translate("MainWindow", "Добавить"))
        self.label_6.setText(_translate("MainWindow", "Введите данные о кофе, в качестве разделителя используйте ;"))
